#!/bin/sh

set -e
git add -A
if [ -z "$1" ]
then
  echo "No commit message given, setting message to: \"`date '+%y%m%d.%Hh%m %z %a'`\""
  git commit -m "\"`date '+%y%m%d.%Hh%m %z %a'`\""
else
  git commit -m "$1"
fi
git push
