#!/bin/zsh

# Print a full horizontal line of dashes
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -;
echo "----------------------------";
echo "------- NVIM SETUP ---------";
echo "----------------------------";

echo "------------------------------------------------------";
echo "---------------- SYMLINK NVIM CONFIG -----------------";
echo "------------------------------------------------------";
set -x;
ln -svf ${HOME}/.dotfiles/.config/nvim ${HOME}/.config/;
set +x;
