#!/bin/sh

if [ ! -d ~/blog/$(date +%y%m) ] then
  mkdir ~/blog/$(date +%y%m)
fi

if [ ! -f ~/blog/$(date +%y%m)/$(date +%y%m%d) ] then
  cp -n ~/blog/blogTemplate.html ~/blog/$(date +%y%m)/$(date +%y%m%d).html
  vim ~/blog/$(date +%y%m)/$(date +%y%m%d).html
else
  echo "you already wrote in your journal today, or at least started"
fi

