#!/bin/sh

year=$(date +%y)

if [ $(date +%m) -gt 6 ]; then
  ((year++))
fi

bycFY="FY${year}"
payroll_date="`date -v+2d '+%y.%m%d'`"
last_payroll_dir="`date -v-12d '+%y.%m%d'` PR"

cd ~/Tresors/${bycFY}/Payroll/
if [ ! -d "$payroll_date PR" ]; then
  mkdir "$payroll_date PR"
  cd "$payroll_date PR"
  mkdir "Clicktime Docs"
  mkdir "Primepay Docs"
  mkdir "Ref Docs"
  cp "/Users/th/Tresors/$bycFY/Payroll/$last_payroll_dir/Primepay docs/TimeSht.PDF" "$payroll_date Payroll.pdf"
fi
