#!/bin/bash

find_FY() {
  if [ "$((`date '+%m'` > 6))" ]
  then
    echo "$((`date '+%y'` + 1))"
  else
    echo `date '+%y'`
  fi
}

month=$(date +%m)
year=$(date +%y)

if [ $month -gt 6 ]; then
  ((year++))
fi
bycFY="FY${year}"
cd ~/Tresors/${bycFY}/Payroll/

payroll_date="`date -v+2d '+%y%m%d'`"
last_payroll_dir="`date -v-12d '+%y%m%d'` PR"
if [ ! -d "$payroll_date PR" ]; then
  mkdir "$payroll_date PR"
  cd "$payroll_date PR"
  mkdir "Clicktime Docs"
  mkdir "Primepay Docs"
  mkdir "Ref Docs"
  cp "/Users/th/Tresors/$bycFY/Payroll/$last_payroll_dir/Primepay docs/TimeSht.PDF" "$payroll_date Payroll.pdf"
fi
